grocery/urls.py
from django.urls import path

from . import views

app_name = "grocery"
urlpatterns = [
    # path("", views.index, name="index"),
    path("<int:storage_id>/", views.detail, name="detail"),
    # path("<int:storage_id>/store", views.store, name="store"),

    path("", views.IndexView.as_view(), name="index"),
    # path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:storage_id>/store", views.store, name="store"),
    path("<int:storage_id>/ticket", views.ticket, name="ticket"),
    path("<int:storage_id>/upload", views.upload, name="upload"),
    path("<int:storage_id>/savetiquet", views.savetiquet, name="savetiquet"),
]

ticketreader/urls.py
# from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    # path('admin/', admin.site.urls),
    path('grocery/', include("grocery.urls")),
] # + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

grocery/models.py
import datetime
from time import timezone
from django.db import models
from django.utils.timezone import now

from django.contrib.auth.models import User


# Create your models here.

class Storage(models.Model):
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def __str__(self) -> str:
        return self.name


class Item(models.Model):

    UNIT_KILO = "KL"
    UNIT_GRAM = "GR"
    UNIT_UNIT = "UN"
    UNIT_PACK = "PK"
    UNIT_LITRE = "LI"
    UNIT_OTHER = "OT"
    UNIT_PIECES = "PI"

    UNIT_CHOICES = [
        (UNIT_UNIT, 'Unitats'),
        (UNIT_PIECES, 'Peces'),
        (UNIT_KILO, 'Kilos'),
        (UNIT_GRAM, 'Grams'),
        (UNIT_PACK, 'Paquets'),
        (UNIT_LITRE, 'Litres'),
        (UNIT_OTHER, 'Altres'),
    ]

    storage = models.ForeignKey(Storage, on_delete=models.RESTRICT)
    user = models.ForeignKey(
        User, on_delete=models.RESTRICT, null=True, default=None)
    name = models.CharField(max_length=200)
    amount = models.IntegerField(default=0)
    unit = models.CharField(
        max_length=2, choices=UNIT_CHOICES, default=UNIT_OTHER)

    def __str__(self) -> str:
        return self.name


class Ticket(models.Model):
    storage = models.ForeignKey(Storage, on_delete=models.RESTRICT)
    user = models.ForeignKey(
        User, on_delete=models.RESTRICT, null=True, default=None)
    total = models.FloatField()
    processedText = models.CharField(max_length=5000)
    uploaded_at = models.DateTimeField(default=now)

    def __str__(self) -> str:
        return self.storage + self.uploaded_at


class Product(models.Model):
    ticket = models.ForeignKey(Ticket, on_delete=models.CASCADE)
    name = models.CharField(max_length=400)
    name_clear = models.CharField(max_length=400)
    price = models.FloatField()

grocery/views.py
import os
import re
import json

from urllib.parse import unquote

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse_lazy # reverse - reverse_lazy (para class based)
from django.views import generic
from django.core.files.storage import default_storage

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.datastructures import MultiValueDictKeyError
from django.http import JsonResponse

from . import utils

from .settings import UPLOAD_PATH_TICKETS
# from django.template import loader

from .models import Storage, Item, Ticket, Product

# Create your views here.


@login_required
def store(request, storage_id):
    storage = get_object_or_404(Storage, pk=storage_id)

    try:

        if (not len(request.POST["name"])):
            raise KeyError

        i = Item.objects.create(
            storage=storage, user=request.user, name=request.POST["name"],
            amount=int('0'+(request.POST['amount'])), unit=request.POST['unit'])
        i.save()

    except (KeyError):
        return render(request, "grocery/detail.html", {"storage": storage, "unit_choices": Item.UNIT_CHOICES, "error_message": "El producte no te nom i no s'ha introduït"})

    else:
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def upload(request, storage_id):
    storage = get_object_or_404(Storage, pk=storage_id)

    text = "Hi ha hagut un error"
    items = []

    if request.method == 'POST':

        try:
            img_stream = request.FILES['croppedImage']

            # print(request.FILES, request.POST, img_stream)
            #  img_stream = base64.b64encode(img_stream).decode()
            filename = img_stream.name
            filepath = os.path.join(UPLOAD_PATH_TICKETS, filename)

            if not img_stream or filename == '' or not utils.allowed_file(img_stream):
                return JsonResponse({"error_message": "No s'ha pogut carregar la imatge"}, safe=False)

            # todo ok save the file
            with default_storage.open(filepath, 'wb+') as destination:
                for chunk in img_stream.chunks():
                    destination.write(chunk)

            # Reading image using OCR
            text = utils.get_img_text(filepath)
            print(text)
            productes = utils.get_products(text)
            print(productes)
            items = json.loads(productes)
            print(items)

        except MultiValueDictKeyError:
            return JsonResponse({"error_message": "MultiValueDictKeyError"}, safe=False)
        except json.decoder.JSONDecodeError:
            return JsonResponse({"error_message": "JSONDecodeError"}, safe=False)

# .replace("\n", "<br>")
    return JsonResponse({"error_message": text, "items_processed": items}, safe=False)


@login_required
def savetiquet(request, storage_id):
    storage = get_object_or_404(Storage, pk=storage_id)
    try:

        if (not len(request.POST['raw-text'])):
            raise KeyError

        total = 0
        clean_productes = {}

        for i in request.POST.items():

            key = i[0]
            value = i[1]

            key = key.replace("%5B", "[").replace("%5D", "]")
            # print(key.replace("%5B", "[").replace("%5D", "]"))

            if key.find("producte") == -1:
                continue

            id = (re.findall(r'\d+', key)[0])
            key = (re.findall(r'(name|amount|price|unit)', key)[0])

            if id not in clean_productes.keys():
                clean_productes[id] = {}

            if key not in clean_productes[id].keys():
                clean_productes[id][key] = ""

            clean_productes[id][key] = value  # request.POST.get(og_i)
            if (key == "price"):
                total += float(value)

        tiquet = Ticket.objects.create(
            user=request.user,
            storage=storage,
            total=total,
            processedText=unquote(request.POST['raw-text']).replace("+", " ")
        )
        tiquet.save()

        print(clean_productes)

        for id in clean_productes.keys():

            values = clean_productes[id]

            print(values)

            item = Item.objects.create(
                storage=storage,
                user=request.user,
                name=unquote(values["name"]).replace("+", " "),
                unit=values["unit"],
                amount=values["amount"]
            )
            print(item)
            item.save()

            prod = Product.objects.create(
                ticket=tiquet,
                name=unquote(values["name"]).replace("+", " "),
                # name_clear=i["unit"],
                price=float(values["price"])
            )
            print(prod)
            prod.save()

    except KeyError as e:
        
        tiquet.delete()
        return render(request, "grocery/detail.html", {"storage": storage, "unit_choices": Item.UNIT_CHOICES, "error_message": e})

    # return HttpResponseRedirect(url('grocery:detail', storage.id))
    return HttpResponseRedirect("/grocery/" + storage.id)


@login_required
def ticket(request, storage_id):
    storage = get_object_or_404(Storage, pk=storage_id)

    return render(request, "grocery/ticket.html", {"storage": storage, "unit_choices": Item.UNIT_CHOICES})


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = "grocery/index.html"
    context_object_name = "latest_storage_list"

    def get_queryset(self):
        try:
            return Storage.objects.filter(users=self.request.user)
        except (Storage.DoesNotExist):
            return []


@login_required
def detail(request, storage_id):
    storage = get_object_or_404(Storage, pk=storage_id)
    return render(request, "grocery/detail.html", {"storage": storage, "unit_choices": Item.UNIT_CHOICES})


# DEPRECATED ------------------------------


@login_required
def index(request):
    latest_storage_list = Storage.objects.order_by("name")[:5]
    context = {"latest_storage_list": latest_storage_list}
    return render(request, "grocery/index.html", context)

    '''
    template = loader.get_template('grocery/index.html')
    context = {
        "latest_storage_list" : latest_storage_list
    }
    return HttpResponse(template.render(context))
    '''


@method_decorator(login_required, name='dispatch')
class DetailView(generic.DetailView):
    model = Storage
    template_name = "grocery/detail.html"

# DEPRECATED

    '''
    try:
        storage = Storage.objects.get(pk=storage_id)
    except Storage.DoesNotExist:
        raise Http404("Storage does not exist")

    return render(request, "grocery/detail.html", {"storage":storage})
    '''

grocery/templates/grocery/detail.html
{% include "grocery/head.html" %}
<div class="container">
    <form action="{% url 'grocery:store' storage.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ storage.name }}</h1>
            </legend>
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <div class="row mb-4">

                <div class="col-md-6">
                    <label for="name" class="form-label">Nou producte</label>
                    <input id="name" class="form-control" type="text" name="name" maxlength="100" required />
                </div>

                <div class="col-md-3">
                    <label for="amount" class="form-label">Quantitat</label>
                    <input id="amount" class="form-control" type="number" name="amount" />
                </div>

                <div class="col-md-3">
                    <label for="unit" class="form-label">&nbsp;</label>
                    <select title="Unitat" id="unit" class="form-control" name="unit">
                        {% for unit in unit_choices %}
                        <option value="{{unit.0}}">{{unit.1}}</option>
                        {% endfor %}
                    </select>
                </div>

            </div>

        </fieldset>
        <input type="submit" class="btn btn-sm btn-success" value="Afegeix producte" />
        <a class="btn btn-sm btn-primary" href="{% url 'grocery:ticket' storage.id %}" type="btn">Nou tiquet</a>
    </form>

    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Ítem</th>
                <th>Quantitat</th>
                <th>Unitats</th>
            </tr>
        </thead>
        <tbody>
            {% for item in storage.item_set.all reversed %}
            <tr>
                <td>{{ item.name }}</td>
                <td>{{ item.amount }}</td>
                <td>{{ item.get_unit_display }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
{% include "grocery/foot.html" %}

grocery/templates/grocery/foot.html
{% load static %}
<script src="{% static 'grocery/js/jquery-3.6.4.min.js' %}"></script>
<script src="{% static 'grocery/js/popper.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'grocery/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'grocery/js/fa-all.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'grocery/js/cropper.js' %}"></script>
<script src="{% static 'grocery/js/jquery-cropper.min.js' %}"></script>
</body>

</html>

grocery/templates/grocery/head.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    {% load static %}
    <link rel="stylesheet" href="{% static 'grocery/css/bootstrap.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'grocery/css/fa-all.min.css' %}" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'grocery/css/cropper.css' %}">
    <link rel="stylesheet" href="{% static 'grocery/css/style.css' %}">
</head>

<body>

    <span id="user-logged"><i class="fa fa-user-circle"></i> {{request.user.username}}</span>

grocery/templates/grocery/index.html
{% include "grocery/head.html" %}

<div class="container">
    
    {% if latest_storage_list %}
    <div class="storages">
        {% for storage in latest_storage_list %}
    <h2><a href="{% url 'grocery:detail' storage.id %}">{{ storage.name }}</a></li>
        {% endfor %}
    </div>
    {% else %}
    <p>No hi ha cap magatzem disponible.</p>
    {% endif %}
</div>

{% include "grocery/foot.html" %}

grocery/templates/grocery/ticket.html
{% include "grocery/head.html" %}
{% load static %}

<div id="loading-frame" class="d-none"></div>
<div class="container">
    <form id="form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <input id="inputImage" class="form-control mb-3" name="ticket" type="file" accept="image/*" />
            <a class="btn btn-primary btn-sm" href="{% url 'grocery:detail' storage.id %}">Torna</a>
            <input type="submit" class="btn btn-sm btn-success" value="Envia" disabled />
        </div>
        <label id="error" class="text-danger"></label>
        <div class="d-none">
            <select title="Unitats" name="" id="select-units" class="form-control">
                {% for unit in unit_choices %}
                <option value="{{unit.0}}">{{unit.1}}</option>
                {% endfor %}
            </select>
        </div>
    </form>

    <div class="img-container img-cropper">
        <img id="image" class=""/>
    </div>

    <div id="img-result-container" class="d-none">
        <img id="img-result" class="img-fluid" src="{% static 'grocery/ticket_tmp/tiquet.jpg' %}?t={% now 'd' %}" />
    </div>
    <form action="{% url 'grocery:savetiquet' storage.id %}" method="post">
        <div id="form-result"></div>
        {% csrf_token %}
        <textarea id="result" name="raw-text" class="d-none"></textarea>
    </form>

    
</div>

{% include "grocery/foot.html" %}

<script src="{% static 'grocery/js/main.js' %}"></script>